export sites = "cel.dev/expr:cel.dev/expr:force \
           gopkg.in/yaml.v2:gopkg.in/yaml.v2:force \
           golang.org/x/net:golang.org/x/net:force \
           golang.org/x/sys:golang.org/x/sys:force \
           gopkg.in/yaml.v3:gopkg.in/yaml.v3:force \
           golang.org/x/sync:golang.org/x/sync:force \
           golang.org/x/term:golang.org/x/term:force \
           golang.org/x/time:golang.org/x/time:force \
           golang.org/x/text:golang.org/x/text:force \
           go.yaml.in/yaml/v2:go.yaml.in/yaml/v2:force \
           golang.org/x/crypto:golang.org/x/crypto:force \
           golang.org/x/oauth2:golang.org/x/oauth2:force \
           cloud.google.com/go:cloud.google.com/go:force \
           google.golang.org/api:google.golang.org/api:force \
           github.com/pkg/errors:github.com/pkg/errors:force \
           github.com/google/uuid:github.com/google/uuid:force \
           github.com/gorilla/css:github.com/gorilla/css:force \
           google.golang.org/grpc:google.golang.org/grpc:force \
           github.com/beorn7/perks:github.com/beorn7/perks:force \
           github.com/go-logr/logr:github.com/go-logr/logr:force \
           github.com/go-logr/stdr:github.com/go-logr/stdr:force \
           github.com/cncf/xds/go:github.com/cncf/xds/go/go:force \
           github.com/olebedev/when:github.com/olebedev/when:force \
           github.com/urfave/cli/v2:github.com/urfave/cli/v2:force \
           github.com/google/s2a-go:github.com/google/s2a-go:force \
           github.com/stretchr/objx:github.com/stretchr/objx:force \
           go.opentelemetry.io/otel:go.opentelemetry.io/otel:force \
           firebase.google.com/go/v4:firebase.google.com/go/v4:force \
           cloud.google.com/go/iam:cloud.google.com/go/iam/iam:force \
           github.com/AlekSi/pointer:github.com/AlekSi/pointer:force \
           github.com/xrash/smetrics:github.com/xrash/smetrics:force \
           github.com/BurntSushi/toml:github.com/BurntSushi/toml:force \
           github.com/davecgh/go-spew:github.com/davecgh/go-spew:force \
           github.com/golang/protobuf:github.com/golang/protobuf:force \
           google.golang.org/genproto:google.golang.org/genproto:force \
           google.golang.org/protobuf:google.golang.org/protobuf:force \
           cloud.google.com/go/auth:cloud.google.com/go/auth/auth:force \
           github.com/emersion/go-smtp:github.com/emersion/go-smtp:force \
           github.com/mattn/go-sqlite3:github.com/mattn/go-sqlite3:force \
           github.com/stretchr/testify:github.com/stretchr/testify:force \
           github.com/aymerick/douceur:github.com/aymerick/douceur:force \
           github.com/emersion/go-sasl:github.com/emersion/go-sasl:force \
           github.com/gorilla/websocket:github.com/gorilla/websocket:force \
           github.com/cespare/xxhash/v2:github.com/cespare/xxhash/v2:force \
           github.com/felixge/httpsnoop:github.com/felixge/httpsnoop:force \
           github.com/golang-jwt/jwt/v4:github.com/golang-jwt/jwt/v4:force \
           github.com/golang-jwt/jwt/v5:github.com/golang-jwt/jwt/v5:force \
           github.com/munnerz/goautoneg:github.com/munnerz/goautoneg:force \
           github.com/prometheus/common:github.com/prometheus/common:force \
           github.com/prometheus/procfs:github.com/prometheus/procfs:force \
           github.com/MicahParks/keyfunc:github.com/MicahParks/keyfunc:force \
           github.com/go-jose/go-jose/v4:github.com/go-jose/go-jose/v4:force \
           github.com/pmezard/go-difflib:github.com/pmezard/go-difflib:force \
           github.com/spiffe/go-spiffe/v2:github.com/spiffe/go-spiffe/v2:force \
           go.opentelemetry.io/auto/sdk:go.opentelemetry.io/auto/sdk/sdk:force \
           go.opentelemetry.io/otel/sdk:go.opentelemetry.io/otel/sdk/sdk:force \
           google.golang.org/appengine/v2:google.golang.org/appengine/v2:force \
           cloud.google.com/go/storage:cloud.google.com/go/storage/storage:force \
           github.com/stripe/stripe-go/v74:github.com/stripe/stripe-go/v74:force \
           github.com/googleapis/gax-go:github.com/googleapis/gax-go/v2:force \
           github.com/cpuguy83/go-md2man/v2:github.com/cpuguy83/go-md2man/v2:force \
           github.com/planetscale/vtprotobuf:github.com/planetscale/vtprotobuf:force \
           go.opentelemetry.io/otel/trace:go.opentelemetry.io/otel/trace/trace:force \
           cloud.google.com/go/firestore:cloud.google.com/go/firestore/firestore:force \
           github.com/gabriel-vasile/mimetype:github.com/gabriel-vasile/mimetype:force \
           github.com/microcosm-cc/bluemonday:github.com/microcosm-cc/bluemonday:force \
           github.com/prometheus/client_model:github.com/prometheus/client_model:force \
           github.com/russross/blackfriday/v2:github.com/russross/blackfriday/v2:force \
           go.opentelemetry.io/otel/metric:go.opentelemetry.io/otel/metric/metric:force \
           github.com/prometheus/client_golang:github.com/prometheus/client_golang:force \
           cloud.google.com/go/monitoring:cloud.google.com/go/monitoring/monitoring:force \
           github.com/SherClockHolmes/webpush-go:github.com/SherClockHolmes/webpush-go:force \
           cloud.google.com/go/longrunning:cloud.google.com/go/longrunning/longrunning:force \
           go.opentelemetry.io/otel/sdk/metric:go.opentelemetry.io/otel/sdk/metric/sdk/metric:force \
           github.com/envoyproxy/protoc-gen-validate:github.com/envoyproxy/protoc-gen-validate:force \
           cloud.google.com/go/auth/oauth2adapt:cloud.google.com/go/auth/oauth2adapt/auth/oauth2adapt:force \
           cloud.google.com/go/compute/metadata:cloud.google.com/go/compute/metadata/compute/metadata:force \
           github.com/envoyproxy/go-control-plane/envoy:github.com/envoyproxy/go-control-plane/envoy/envoy:force \
           go.opentelemetry.io/contrib/detectors/gcp:go.opentelemetry.io/contrib/detectors/gcp/detectors/gcp:force \
           google.golang.org/genproto/googleapis/api:google.golang.org/genproto/googleapis/api/googleapis/api:force \
           google.golang.org/genproto/googleapis/rpc:google.golang.org/genproto/googleapis/rpc/googleapis/rpc:force \
           github.com/googleapis/enterprise-certificate-proxy:github.com/googleapis/enterprise-certificate-proxy:force \
           go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp:go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/instrumentation/net/http/otelhttp:force \
           github.com/GoogleCloudPlatform/opentelemetry-operations-go/detectors/gcp:github.com/GoogleCloudPlatform/opentelemetry-operations-go/detectors/gcp/detectors/gcp:force \
           github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/metric:github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/metric/exporter/metric:force \
           github.com/GoogleCloudPlatform/opentelemetry-operations-go/internal/resourcemapping:github.com/GoogleCloudPlatform/opentelemetry-operations-go/internal/resourcemapping/internal/resourcemapping:force \
           go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc:go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/instrumentation/google.golang.org/grpc/otelgrpc:force"

do_compile:prepend() {
    cd ${S}/src/${GO_IMPORT}
    for s in $sites; do
        site_dest=$(echo $s | cut -d: -f1)
        site_source=$(echo $s | cut -d: -f2)
        force_flag=$(echo $s | cut -d: -f3)
        mkdir -p vendor.copy/$site_dest
        if [ -n "$force_flag" ]; then
            echo "[INFO] $site_dest: force copying .go files"
            rm -rf vendor.copy/$site_dest
            rsync -a --exclude='vendor/' --exclude='.git/' vendor.fetch/$site_source/ vendor.copy/$site_dest
        else
            [ -n "$(ls -A vendor.copy/$site_dest/*.go 2> /dev/null)" ] && { echo "[INFO] vendor.fetch/$site_source -> $site_dest: go copy skipped (files present)" ; true ; } || { echo "[INFO] $site_dest: copying .go files" ; rsync -a --exclude='vendor/' --exclude='.git/' vendor.fetch/$site_source/ vendor.copy/$site_dest ; }
        fi
    done
}
