#       gopkg.in/yaml.v2 v2.4.0
# [1] git ls-remote https://github.com/go-yaml/yaml 7649d4548cb53a614db133b2a8ac1f31859dda8c
SRCREV_yaml.v2="7649d4548cb53a614db133b2a8ac1f31859dda8c"
SRC_URI += "git://github.com/go-yaml/yaml;name=yaml.v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/yaml.v2"

#       go.opencensus.io v0.24.0
# [1] git ls-remote https://github.com/census-instrumentation/opencensus-go b1a01ee95db0e690d91d7193d037447816fae4c5
SRCREV_go.opencensus.io="b1a01ee95db0e690d91d7193d037447816fae4c5"
SRC_URI += "git://github.com/census-instrumentation/opencensus-go;name=go.opencensus.io;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opencensus.io"

#       golang.org/x/net v0.8.0
# [1] git ls-remote https://go.googlesource.com/net dfa2b5dffd96fb2ae13e7d182501f0bce044a0a4
SRCREV_net="dfa2b5dffd96fb2ae13e7d182501f0bce044a0a4"
SRC_URI += "git://go.googlesource.com/net;name=net;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/net"

#       golang.org/x/sys v0.6.0
# [1] git ls-remote https://go.googlesource.com/sys c7a1bf9a0b0aa7c0c0e35a435924dd68e64d1653
SRCREV_sys="c7a1bf9a0b0aa7c0c0e35a435924dd68e64d1653"
SRC_URI += "git://go.googlesource.com/sys;name=sys;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/sys"

#       gopkg.in/yaml.v3 v3.0.1
# [1] git ls-remote https://github.com/go-yaml/yaml f6f7691b1fdeb513f56608cd2c32c51f8194bf51
SRCREV_yaml.v3="f6f7691b1fdeb513f56608cd2c32c51f8194bf51"
SRC_URI += "git://github.com/go-yaml/yaml;name=yaml.v3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/yaml.v3"

#       golang.org/x/sync v0.1.0
# [1] git ls-remote https://go.googlesource.com/sync 8fcdb60fdcc0539c5e357b2308249e4e752147f1
SRCREV_sync="8fcdb60fdcc0539c5e357b2308249e4e752147f1"
SRC_URI += "git://go.googlesource.com/sync;name=sync;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/sync"

#       golang.org/x/term v0.6.0
# [1] git ls-remote https://go.googlesource.com/term 0edf009663f942c41572b65d537ee2636e92180c
SRCREV_term="0edf009663f942c41572b65d537ee2636e92180c"
SRC_URI += "git://go.googlesource.com/term;name=term;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/term"

#       golang.org/x/time v0.3.0
# [1] git ls-remote https://go.googlesource.com/time 2c09566ef13fb5556401ddff3c53c3dbc2a42dac
SRCREV_time="2c09566ef13fb5556401ddff3c53c3dbc2a42dac"
SRC_URI += "git://go.googlesource.com/time;name=time;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/time"

#       golang.org/x/text v0.8.0
# [1] git ls-remote https://go.googlesource.com/text 9db913aaf20ced01b7a130d9fb222d74a1339fa6
SRCREV_text="9db913aaf20ced01b7a130d9fb222d74a1339fa6"
SRC_URI += "git://go.googlesource.com/text;name=text;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/text"

#       golang.org/x/crypto v0.7.0
# [1] git ls-remote https://go.googlesource.com/crypto 776e461a4e6d8b372a43c72122c5c28cfc40dca2
SRCREV_crypto="776e461a4e6d8b372a43c72122c5c28cfc40dca2"
SRC_URI += "git://go.googlesource.com/crypto;name=crypto;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/crypto"

#       golang.org/x/oauth2 v0.6.0
# [1] git ls-remote https://go.googlesource.com/oauth2 62b4eedd7210c3ff2fc694318a8a312b96f01a74
SRCREV_oauth2="62b4eedd7210c3ff2fc694318a8a312b96f01a74"
SRC_URI += "git://go.googlesource.com/oauth2;name=oauth2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/oauth2"

#       cloud.google.com/go v0.110.0
# [1] git ls-remote https://github.com/googleapis/google-cloud-go b4d0ff0e4e7be0f8048416f13db56d1c7bb6bec0
SRCREV_go="b4d0ff0e4e7be0f8048416f13db56d1c7bb6bec0"
SRC_URI += "git://github.com/googleapis/google-cloud-go;name=go;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/cloud.google.com/go"

#       github.com/kr/pretty v0.3.1
# [1] git ls-remote https://github.com/kr/pretty 3cd153a126da607b78d1762779b1e1054f9889fc
SRCREV_pretty="3cd153a126da607b78d1762779b1e1054f9889fc"
SRC_URI += "git://github.com/kr/pretty;name=pretty;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/kr/pretty"

#       golang.org/x/xerrors v0.0.0-20220907171357-04be3eba64a2
# [1] git ls-remote https://go.googlesource.com/xerrors 04be3eba64a22a838cdb17b8dca15a52871c08b4
SRCREV_xerrors="04be3eba64a22a838cdb17b8dca15a52871c08b4"
SRC_URI += "git://go.googlesource.com/xerrors;name=xerrors;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/xerrors"

#       google.golang.org/api v0.114.0
# [1] git ls-remote https://github.com/googleapis/google-api-go-client f79df4875aea4520e4aff5c5ebceb9e01b7b60a2
SRCREV_api="f79df4875aea4520e4aff5c5ebceb9e01b7b60a2"
SRC_URI += "git://github.com/googleapis/google-api-go-client;name=api;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/api"

#       github.com/pkg/errors v0.9.1
# [1] git ls-remote https://github.com/pkg/errors 614d223910a179a466c1767a985424175c39b465
SRCREV_errors="614d223910a179a466c1767a985424175c39b465"
SRC_URI += "git://github.com/pkg/errors;name=errors;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/pkg/errors"

#       github.com/google/uuid v1.3.0
# [1] git ls-remote https://github.com/google/uuid 44b5fee7c49cf3bcdf723f106b36d56ef13ccc88
SRCREV_uuid="44b5fee7c49cf3bcdf723f106b36d56ef13ccc88"
SRC_URI += "git://github.com/google/uuid;name=uuid;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/uuid"

#       google.golang.org/grpc v1.54.0
# [1] git ls-remote https://github.com/grpc/grpc-go 2997e84fd8d18ddb000ac6736129b48b3c9773ec
SRCREV_grpc="2997e84fd8d18ddb000ac6736129b48b3c9773ec"
SRC_URI += "git://github.com/grpc/grpc-go;name=grpc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/grpc"

#       cloud.google.com/go/iam v0.13.0
# [1] git ls-remote https://github.com/googleapis/google-cloud-go c2bf628da9b4f30df75608ffa77c2fb8d6a6cf8d
SRCREV_iam="c2bf628da9b4f30df75608ffa77c2fb8d6a6cf8d"
SRC_URI += "git://github.com/googleapis/google-cloud-go;name=iam;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/cloud.google.com/go/iam"

#       github.com/beorn7/perks v1.0.1
# [1] git ls-remote https://github.com/beorn7/perks 37c8de3658fcb183f997c4e13e8337516ab753e6
SRCREV_perks="37c8de3658fcb183f997c4e13e8337516ab753e6"
SRC_URI += "git://github.com/beorn7/perks;name=perks;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/beorn7/perks"

#       github.com/olebedev/when v0.0.0-20221205223600-4d190b02b8d8
# [1] git ls-remote https://github.com/olebedev/when 4d190b02b8d838367565269cfaee8b94b78ba25d
SRCREV_when="4d190b02b8d838367565269cfaee8b94b78ba25d"
SRC_URI += "git://github.com/olebedev/when;name=when;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/olebedev/when"

#       github.com/urfave/cli/v2 v2.25.1
# [1] git ls-remote https://github.com/urfave/cli 04369984a0d0f443443dba1da409871546110639
SRCREV_cli-v2="04369984a0d0f443443dba1da409871546110639"
SRC_URI += "git://github.com/urfave/cli;name=cli-v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/urfave/cli/v2"

#       github.com/google/go-cmp v0.5.9
# [1] git ls-remote https://github.com/google/go-cmp a97318bf6562f2ed2632c5f985db51b1bc5bdcd0
SRCREV_go-cmp="a97318bf6562f2ed2632c5f985db51b1bc5bdcd0"
SRC_URI += "git://github.com/google/go-cmp;name=go-cmp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/go-cmp"

#       github.com/stretchr/objx v0.5.0
# [1] git ls-remote https://github.com/stretchr/objx 50a2c064be99303c5dddf725da60e30fbc4f6ede
SRCREV_objx="50a2c064be99303c5dddf725da60e30fbc4f6ede"
SRC_URI += "git://github.com/stretchr/objx;name=objx;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/stretchr/objx"

#       firebase.google.com/go/v4 v4.10.0
# [1] git ls-remote https://github.com/firebase/firebase-admin-go 1d245771f556db75b76b32a793b931be6f39c630
SRCREV_v4="1d245771f556db75b76b32a793b931be6f39c630"
SRC_URI += "git://github.com/firebase/firebase-admin-go;name=v4;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/firebase.google.com/go/v4"

#       github.com/AlekSi/pointer v1.2.0
# [1] git ls-remote https://github.com/AlekSi/pointer 039be97b958cc3cbeb2329617d2e493bd2331fac
SRCREV_pointer="039be97b958cc3cbeb2329617d2e493bd2331fac"
SRC_URI += "git://github.com/AlekSi/pointer;name=pointer;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/AlekSi/pointer"

#       github.com/xrash/smetrics v0.0.0-20201216005158-039620a65673
# [1] git ls-remote https://github.com/xrash/smetrics 039620a656736e6ad994090895784a7af15e0b80
SRCREV_smetrics="039620a656736e6ad994090895784a7af15e0b80"
SRC_URI += "git://github.com/xrash/smetrics;name=smetrics;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/xrash/smetrics"

#       github.com/BurntSushi/toml v1.2.1
# [1] git ls-remote https://github.com/BurntSushi/toml 74c008f3d2dcb9c295248aada067301a0d810932
SRCREV_toml="74c008f3d2dcb9c295248aada067301a0d810932"
SRC_URI += "git://github.com/BurntSushi/toml;name=toml;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/BurntSushi/toml"

#       github.com/davecgh/go-spew v1.1.1
# [1] git ls-remote https://github.com/davecgh/go-spew 8991bc29aa16c548c550c7ff78260e27b9ab7c73
SRCREV_go-spew="8991bc29aa16c548c550c7ff78260e27b9ab7c73"
SRC_URI += "git://github.com/davecgh/go-spew;name=go-spew;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/davecgh/go-spew"

#       github.com/golang/protobuf v1.5.3
# [1] git ls-remote https://github.com/golang/protobuf 5d5e8c018a13017f9d5b8bf4fad64aaa42a87308
SRCREV_protobuf="5d5e8c018a13017f9d5b8bf4fad64aaa42a87308"
SRC_URI += "git://github.com/golang/protobuf;name=protobuf;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/golang/protobuf"

#       google.golang.org/genproto v0.0.0-20230330200707-38013875ee22
# [1] git ls-remote https://github.com/googleapis/go-genproto 38013875ee22bcec7029a9daf0847c04f95accac
SRCREV_genproto="38013875ee22bcec7029a9daf0847c04f95accac"
SRC_URI += "git://github.com/googleapis/go-genproto;name=genproto;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/genproto"

#       google.golang.org/protobuf v1.30.0
# [1] git ls-remote https://github.com/protocolbuffers/protobuf-go f221882bfb484564f1714ae05f197dea2c76898d
SRCREV_google.golang.org-protobuf="f221882bfb484564f1714ae05f197dea2c76898d"
SRC_URI += "git://github.com/protocolbuffers/protobuf-go;name=google.golang.org-protobuf;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/protobuf"

#       cloud.google.com/go/storage v1.30.1
# [1] git ls-remote https://github.com/googleapis/google-cloud-go c537b5101cb92da8df95f2d34334b3db54731d5c
SRCREV_storage="c537b5101cb92da8df95f2d34334b3db54731d5c"
SRC_URI += "git://github.com/googleapis/google-cloud-go;name=storage;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/cloud.google.com/go/storage"

#       github.com/emersion/go-smtp v0.16.0
# [1] git ls-remote https://github.com/emersion/go-smtp 49b17434419d525c481b36016d2287a8ee507e6c
SRCREV_go-smtp="49b17434419d525c481b36016d2287a8ee507e6c"
SRC_URI += "git://github.com/emersion/go-smtp;name=go-smtp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/emersion/go-smtp"

#       github.com/mattn/go-sqlite3 v1.14.16
# [1] git ls-remote https://github.com/mattn/go-sqlite3 bce3773726b3f7ef4609661a0f0f4fb00a0df761
SRCREV_go-sqlite3="bce3773726b3f7ef4609661a0f0f4fb00a0df761"
SRC_URI += "git://github.com/mattn/go-sqlite3;name=go-sqlite3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mattn/go-sqlite3"

#       github.com/stretchr/testify v1.8.1
# [1] git ls-remote https://github.com/stretchr/testify b747d7c5f853d017ddbc5e623d026d7fc2770a58
SRCREV_testify="b747d7c5f853d017ddbc5e623d026d7fc2770a58"
SRC_URI += "git://github.com/stretchr/testify;name=testify;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/stretchr/testify"

#       cloud.google.com/go/compute v1.19.0
# [1] git ls-remote https://github.com/googleapis/google-cloud-go 3c279308301a8276ba79082ea44ad47d5861e8c0
SRCREV_compute="3c279308301a8276ba79082ea44ad47d5861e8c0"
SRC_URI += "git://github.com/googleapis/google-cloud-go;name=compute;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/cloud.google.com/go/compute"

#       github.com/emersion/go-sasl v0.0.0-20220912192320-0145f2c60ead
# [1] git ls-remote https://github.com/emersion/go-sasl 0145f2c60eadf52ac05a550c127adce4a266feeb
SRCREV_go-sasl="0145f2c60eadf52ac05a550c127adce4a266feeb"
SRC_URI += "git://github.com/emersion/go-sasl;name=go-sasl;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/emersion/go-sasl"

#       google.golang.org/appengine v1.6.7
# [1] git ls-remote https://github.com/golang/appengine 5d1c1d03f8703c2e81478d9a30e9afa2d3e4bd8a
SRCREV_appengine="5d1c1d03f8703c2e81478d9a30e9afa2d3e4bd8a"
SRC_URI += "git://github.com/golang/appengine;name=appengine;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/appengine"

#       github.com/gorilla/websocket v1.5.0
# [1] git ls-remote https://github.com/gorilla/websocket 9111bb834a68b893cebbbaed5060bdbc1d9ab7d2
SRCREV_websocket="9111bb834a68b893cebbbaed5060bdbc1d9ab7d2"
SRC_URI += "git://github.com/gorilla/websocket;name=websocket;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gorilla/websocket"

#       github.com/cespare/xxhash/v2 v2.2.0
# [1] git ls-remote https://github.com/cespare/xxhash a76eb16a93c1e30527c073ca831d9048b4b935f6
SRCREV_xxhash-v2="a76eb16a93c1e30527c073ca831d9048b4b935f6"
SRC_URI += "git://github.com/cespare/xxhash;name=xxhash-v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cespare/xxhash/v2"

#       github.com/golang-jwt/jwt/v4 v4.5.0
# [1] git ls-remote https://github.com/golang-jwt/jwt 9358574a7a1a2c8d644f22b6e8de627ba85c58d0
SRCREV_jwt-v4="9358574a7a1a2c8d644f22b6e8de627ba85c58d0"
SRC_URI += "git://github.com/golang-jwt/jwt;name=jwt-v4;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/golang-jwt/jwt/v4"

#       github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
# [1] git ls-remote https://github.com/golang/groupcache 41bb18bfe9da5321badc438f91158cd790a33aa3
SRCREV_groupcache="41bb18bfe9da5321badc438f91158cd790a33aa3"
SRC_URI += "git://github.com/golang/groupcache;name=groupcache;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/golang/groupcache"

#       github.com/prometheus/common v0.42.0
# [1] git ls-remote https://github.com/prometheus/common 66b493f42b757378fbad83e42b0ed441d425a17b
SRCREV_common="66b493f42b757378fbad83e42b0ed441d425a17b"
SRC_URI += "git://github.com/prometheus/common;name=common;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/common"

#       github.com/prometheus/procfs v0.9.0
# [1] git ls-remote https://github.com/prometheus/procfs bb7727a9ca9b3cd1559b42ffa74e13ef7efb6283
SRCREV_procfs="bb7727a9ca9b3cd1559b42ffa74e13ef7efb6283"
SRC_URI += "git://github.com/prometheus/procfs;name=procfs;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/procfs"

#       cloud.google.com/go/firestore v1.9.0
# [1] git ls-remote https://github.com/googleapis/google-cloud-go 756f7bf9cab1a402fe3b496c5cdbbeabf7b5112d
SRCREV_firestore="756f7bf9cab1a402fe3b496c5cdbbeabf7b5112d"
SRC_URI += "git://github.com/googleapis/google-cloud-go;name=firestore;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/cloud.google.com/go/firestore"

#       github.com/MicahParks/keyfunc v1.9.0
# [1] git ls-remote https://github.com/MicahParks/keyfunc f76c64fa36d9b7e4a96547313dcb651d54aa006b
SRCREV_keyfunc="f76c64fa36d9b7e4a96547313dcb651d54aa006b"
SRC_URI += "git://github.com/MicahParks/keyfunc;name=keyfunc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/MicahParks/keyfunc"

#       github.com/pmezard/go-difflib v1.0.0
# [1] git ls-remote https://github.com/pmezard/go-difflib 792786c7400a136282c1664665ae0a8db921c6c2
SRCREV_go-difflib="792786c7400a136282c1664665ae0a8db921c6c2"
SRC_URI += "git://github.com/pmezard/go-difflib;name=go-difflib;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/pmezard/go-difflib"

#       google.golang.org/appengine/v2 v2.0.2
# [1] git ls-remote https://github.com/golang/appengine d981f2f002d390baf247df350188877249f725e9
SRCREV_appengine-v2="d981f2f002d390baf247df350188877249f725e9"
SRC_URI += "git://github.com/golang/appengine;name=appengine-v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/appengine/v2"

#       github.com/stripe/stripe-go/v74 v74.14.0
# [1] git ls-remote https://github.com/stripe/stripe-go 3339e43118929c33b6689925d4bfedfacc6e704b
SRCREV_v74="3339e43118929c33b6689925d4bfedfacc6e704b"
SRC_URI += "git://github.com/stripe/stripe-go;name=v74;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/stripe/stripe-go/v74"

#       cloud.google.com/go/longrunning v0.4.1
# [1] git ls-remote https://github.com/googleapis/google-cloud-go bd90ad90c1de4495ea270e7d1ba3390a41f88f0a
SRCREV_longrunning="bd90ad90c1de4495ea270e7d1ba3390a41f88f0a"
SRC_URI += "git://github.com/googleapis/google-cloud-go;name=longrunning;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/cloud.google.com/go/longrunning"

#       github.com/googleapis/gax-go/v2 v2.8.0
# [1] git ls-remote https://github.com/googleapis/gax-go 77e4c0b8fc7be000a67e353e2d89cf71ca167cac
SRCREV_gax-go-v2="77e4c0b8fc7be000a67e353e2d89cf71ca167cac"
SRC_URI += "git://github.com/googleapis/gax-go;name=gax-go-v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/googleapis/gax-go/v2"

#       github.com/cpuguy83/go-md2man/v2 v2.0.2
# [1] git ls-remote https://github.com/cpuguy83/go-md2man d97078115282836e16d0dca10b4b42ce60fc70e6
SRCREV_v2="d97078115282836e16d0dca10b4b42ce60fc70e6"
SRC_URI += "git://github.com/cpuguy83/go-md2man;name=v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cpuguy83/go-md2man/v2"

#       github.com/gabriel-vasile/mimetype v1.4.2
# [1] git ls-remote https://github.com/gabriel-vasile/mimetype 6f575b3e3509415374009db9cb81d6eae1fdfefb
SRCREV_mimetype="6f575b3e3509415374009db9cb81d6eae1fdfefb"
SRC_URI += "git://github.com/gabriel-vasile/mimetype;name=mimetype;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gabriel-vasile/mimetype"

#       github.com/prometheus/client_model v0.3.0
# [1] git ls-remote https://github.com/prometheus/client_model 63fb9822ca3ba7a4ba5184071fb8f2ea000a99ef
SRCREV_client_model="63fb9822ca3ba7a4ba5184071fb8f2ea000a99ef"
SRC_URI += "git://github.com/prometheus/client_model;name=client_model;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/client_model"

#       github.com/russross/blackfriday/v2 v2.1.0
# [1] git ls-remote https://github.com/russross/blackfriday 4c9bf9512682b995722660a4196c0013228e2049
SRCREV_blackfriday-v2="4c9bf9512682b995722660a4196c0013228e2049"
SRC_URI += "git://github.com/russross/blackfriday;name=blackfriday-v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/russross/blackfriday/v2"

#       github.com/prometheus/client_golang v1.14.0
# [1] git ls-remote https://github.com/prometheus/client_golang 254e5468413f19fb75cdad45f5ddc0b8c975188c
SRCREV_client_golang="254e5468413f19fb75cdad45f5ddc0b8c975188c"
SRC_URI += "git://github.com/prometheus/client_golang;name=client_golang;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/client_golang"

#       cloud.google.com/go/compute/metadata v0.2.3
# [1] git ls-remote https://github.com/googleapis/google-cloud-go cf8081fada0955a1682ce3fc400b44bc141309c7
SRCREV_metadata="cf8081fada0955a1682ce3fc400b44bc141309c7"
SRC_URI += "git://github.com/googleapis/google-cloud-go;name=metadata;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/cloud.google.com/go/compute/metadata"

#       github.com/matttproud/golang_protobuf_extensions v1.0.4
# [1] git ls-remote https://github.com/matttproud/golang_protobuf_extensions c182affec369e30f25d3eb8cd8a478dee585ae7d
SRCREV_golang_protobuf_extensions="c182affec369e30f25d3eb8cd8a478dee585ae7d"
SRC_URI += "git://github.com/matttproud/golang_protobuf_extensions;name=golang_protobuf_extensions;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/matttproud/golang_protobuf_extensions"

#       github.com/googleapis/enterprise-certificate-proxy v0.2.3
# [1] git ls-remote https://github.com/googleapis/enterprise-certificate-proxy d0957a96ce28f68cd21ce2742c06237f3fa93fbe
SRCREV_enterprise-certificate-proxy="d0957a96ce28f68cd21ce2742c06237f3fa93fbe"
SRC_URI += "git://github.com/googleapis/enterprise-certificate-proxy;name=enterprise-certificate-proxy;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/googleapis/enterprise-certificate-proxy"

